#
# This file has been generated by tools/gen-deps.sh
#

src/include/skabus/skabus.h: src/include/skabus/rpc.h
src/libskabus/skabus-rpc-internal.h: src/include/skabus/rpc.h
src/rpc/skabus-rpcd.h: src/include/skabus/rpc.h
src/libskabus/skabus_rpc_cancel.o src/libskabus/skabus_rpc_cancel.lo: src/libskabus/skabus_rpc_cancel.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_cancel_async.o src/libskabus/skabus_rpc_cancel_async.lo: src/libskabus/skabus_rpc_cancel_async.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_end.o src/libskabus/skabus_rpc_end.lo: src/libskabus/skabus_rpc_end.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_get.o src/libskabus/skabus_rpc_get.lo: src/libskabus/skabus_rpc_get.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_idstr.o src/libskabus/skabus_rpc_idstr.lo: src/libskabus/skabus_rpc_idstr.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_idstr_async.o src/libskabus/skabus_rpc_idstr_async.lo: src/libskabus/skabus_rpc_idstr_async.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_interface_register.o src/libskabus/skabus_rpc_interface_register.lo: src/libskabus/skabus_rpc_interface_register.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_interface_register_async.o src/libskabus/skabus_rpc_interface_register_async.lo: src/libskabus/skabus_rpc_interface_register_async.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_interface_register_cb.o src/libskabus/skabus_rpc_interface_register_cb.lo: src/libskabus/skabus_rpc_interface_register_cb.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_interface_unregister.o src/libskabus/skabus_rpc_interface_unregister.lo: src/libskabus/skabus_rpc_interface_unregister.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_interface_unregister_async.o src/libskabus/skabus_rpc_interface_unregister_async.lo: src/libskabus/skabus_rpc_interface_unregister_async.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_interface_zero.o src/libskabus/skabus_rpc_interface_zero.lo: src/libskabus/skabus_rpc_interface_zero.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_qinfo_zero.o src/libskabus/skabus_rpc_qinfo_zero.lo: src/libskabus/skabus_rpc_qinfo_zero.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_qlist.o src/libskabus/skabus_rpc_qlist.lo: src/libskabus/skabus_rpc_qlist.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_qlist_ack.o src/libskabus/skabus_rpc_qlist_ack.lo: src/libskabus/skabus_rpc_qlist_ack.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_r_notimpl.o src/libskabus/skabus_rpc_r_notimpl.lo: src/libskabus/skabus_rpc_r_notimpl.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_rcancel_ignore.o src/libskabus/skabus_rpc_rcancel_ignore.lo: src/libskabus/skabus_rpc_rcancel_ignore.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_release.o src/libskabus/skabus_rpc_release.lo: src/libskabus/skabus_rpc_release.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_reply.o src/libskabus/skabus_rpc_reply.lo: src/libskabus/skabus_rpc_reply.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_reply_async.o src/libskabus/skabus_rpc_reply_async.lo: src/libskabus/skabus_rpc_reply_async.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_replyv.o src/libskabus/skabus_rpc_replyv.lo: src/libskabus/skabus_rpc_replyv.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_replyv_async.o src/libskabus/skabus_rpc_replyv_async.lo: src/libskabus/skabus_rpc_replyv_async.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_rinfo_pack.o src/libskabus/skabus_rpc_rinfo_pack.lo: src/libskabus/skabus_rpc_rinfo_pack.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_rinfo_unpack.o src/libskabus/skabus_rpc_rinfo_unpack.lo: src/libskabus/skabus_rpc_rinfo_unpack.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_rinfo_zero.o src/libskabus/skabus_rpc_rinfo_zero.lo: src/libskabus/skabus_rpc_rinfo_zero.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_send.o src/libskabus/skabus_rpc_send.lo: src/libskabus/skabus_rpc_send.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_send_async.o src/libskabus/skabus_rpc_send_async.lo: src/libskabus/skabus_rpc_send_async.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_send_cb.o src/libskabus/skabus_rpc_send_cb.lo: src/libskabus/skabus_rpc_send_cb.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendpm.o src/libskabus/skabus_rpc_sendpm.lo: src/libskabus/skabus_rpc_sendpm.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendpm_async.o src/libskabus/skabus_rpc_sendpm_async.lo: src/libskabus/skabus_rpc_sendpm_async.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendq.o src/libskabus/skabus_rpc_sendq.lo: src/libskabus/skabus_rpc_sendq.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendq_async.o src/libskabus/skabus_rpc_sendq_async.lo: src/libskabus/skabus_rpc_sendq_async.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendv.o src/libskabus/skabus_rpc_sendv.lo: src/libskabus/skabus_rpc_sendv.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendv_async.o src/libskabus/skabus_rpc_sendv_async.lo: src/libskabus/skabus_rpc_sendv_async.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendvpm.o src/libskabus/skabus_rpc_sendvpm.lo: src/libskabus/skabus_rpc_sendvpm.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendvpm_async.o src/libskabus/skabus_rpc_sendvpm_async.lo: src/libskabus/skabus_rpc_sendvpm_async.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendvq.o src/libskabus/skabus_rpc_sendvq.lo: src/libskabus/skabus_rpc_sendvq.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_sendvq_async.o src/libskabus/skabus_rpc_sendvq_async.lo: src/libskabus/skabus_rpc_sendvq_async.c src/libskabus/skabus-rpc-internal.h src/include/skabus/rpc.h
src/libskabus/skabus_rpc_start.o src/libskabus/skabus_rpc_start.lo: src/libskabus/skabus_rpc_start.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_start_async.o src/libskabus/skabus_rpc_start_async.lo: src/libskabus/skabus_rpc_start_async.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_update.o src/libskabus/skabus_rpc_update.lo: src/libskabus/skabus_rpc_update.c src/include/skabus/rpc.h
src/libskabus/skabus_rpc_zero.o src/libskabus/skabus_rpc_zero.lo: src/libskabus/skabus_rpc_zero.c src/include/skabus/rpc.h
src/misc/skabus-dyntee-client.o src/misc/skabus-dyntee-client.lo: src/misc/skabus-dyntee-client.c
src/misc/skabus-dyntee.o src/misc/skabus-dyntee.lo: src/misc/skabus-dyntee.c src/include/skabus/config.h
src/misc/skabus-dynteed.o src/misc/skabus-dynteed.lo: src/misc/skabus-dynteed.c
src/rpc/skabus-rpc-client.o src/rpc/skabus-rpc-client.lo: src/rpc/skabus-rpc-client.c src/rpc/skabus-rpcc.h src/include/skabus/config.h
src/rpc/skabus-rpc-daemon.o src/rpc/skabus-rpc-daemon.lo: src/rpc/skabus-rpc-daemon.c src/include/skabus/config.h
src/rpc/skabus-rpcc.o src/rpc/skabus-rpcc.lo: src/rpc/skabus-rpcc.c src/rpc/skabus-rpcc.h src/include/skabus/rpc.h
src/rpc/skabus-rpccctl.o src/rpc/skabus-rpccctl.lo: src/rpc/skabus-rpccctl.c src/rpc/skabus-rpccctl.h
src/rpc/skabus-rpcd.o src/rpc/skabus-rpcd.lo: src/rpc/skabus-rpcd.c src/rpc/skabus-rpcd.h src/include/skabus/rpc.h
src/rpc/skabus_rpccctl.o src/rpc/skabus_rpccctl.lo: src/rpc/skabus_rpccctl.c src/rpc/skabus-rpccctl.h src/include/skabus/rpc.h
src/rpc/skabus_rpcd_client.o src/rpc/skabus_rpcd_client.lo: src/rpc/skabus_rpcd_client.c src/rpc/skabus-rpcd.h src/include/skabus/rpc.h
src/rpc/skabus_rpcd_interface.o src/rpc/skabus_rpcd_interface.lo: src/rpc/skabus_rpcd_interface.c src/rpc/skabus-rpcd.h src/include/skabus/rpc.h
src/rpc/skabus_rpcd_query.o src/rpc/skabus_rpcd_query.lo: src/rpc/skabus_rpcd_query.c src/rpc/skabus-rpcd.h src/include/skabus/rpc.h

ifeq ($(strip $(STATIC_LIBS_ARE_PIC)),)
libskabus.a.xyzzy: src/libskabus/skabus_rpc_cancel.o src/libskabus/skabus_rpc_cancel_async.o src/libskabus/skabus_rpc_end.o src/libskabus/skabus_rpc_get.o src/libskabus/skabus_rpc_idstr.o src/libskabus/skabus_rpc_idstr_async.o src/libskabus/skabus_rpc_interface_register.o src/libskabus/skabus_rpc_interface_register_async.o src/libskabus/skabus_rpc_interface_register_cb.o src/libskabus/skabus_rpc_interface_unregister.o src/libskabus/skabus_rpc_interface_unregister_async.o src/libskabus/skabus_rpc_interface_zero.o src/libskabus/skabus_rpc_qinfo_zero.o src/libskabus/skabus_rpc_qlist.o src/libskabus/skabus_rpc_qlist_ack.o src/libskabus/skabus_rpc_r_notimpl.o src/libskabus/skabus_rpc_rcancel_ignore.o src/libskabus/skabus_rpc_release.o src/libskabus/skabus_rpc_reply.o src/libskabus/skabus_rpc_replyv.o src/libskabus/skabus_rpc_reply_async.o src/libskabus/skabus_rpc_replyv_async.o src/libskabus/skabus_rpc_rinfo_pack.o src/libskabus/skabus_rpc_rinfo_unpack.o src/libskabus/skabus_rpc_rinfo_zero.o src/libskabus/skabus_rpc_send.o src/libskabus/skabus_rpc_send_async.o src/libskabus/skabus_rpc_send_cb.o src/libskabus/skabus_rpc_sendpm.o src/libskabus/skabus_rpc_sendpm_async.o src/libskabus/skabus_rpc_sendq.o src/libskabus/skabus_rpc_sendq_async.o src/libskabus/skabus_rpc_sendv.o src/libskabus/skabus_rpc_sendv_async.o src/libskabus/skabus_rpc_sendvpm.o src/libskabus/skabus_rpc_sendvpm_async.o src/libskabus/skabus_rpc_sendvq.o src/libskabus/skabus_rpc_sendvq_async.o src/libskabus/skabus_rpc_start.o src/libskabus/skabus_rpc_start_async.o src/libskabus/skabus_rpc_update.o src/libskabus/skabus_rpc_zero.o
else
libskabus.a.xyzzy: src/libskabus/skabus_rpc_cancel.lo src/libskabus/skabus_rpc_cancel_async.lo src/libskabus/skabus_rpc_end.lo src/libskabus/skabus_rpc_get.lo src/libskabus/skabus_rpc_idstr.lo src/libskabus/skabus_rpc_idstr_async.lo src/libskabus/skabus_rpc_interface_register.lo src/libskabus/skabus_rpc_interface_register_async.lo src/libskabus/skabus_rpc_interface_register_cb.lo src/libskabus/skabus_rpc_interface_unregister.lo src/libskabus/skabus_rpc_interface_unregister_async.lo src/libskabus/skabus_rpc_interface_zero.lo src/libskabus/skabus_rpc_qinfo_zero.lo src/libskabus/skabus_rpc_qlist.lo src/libskabus/skabus_rpc_qlist_ack.lo src/libskabus/skabus_rpc_r_notimpl.lo src/libskabus/skabus_rpc_rcancel_ignore.lo src/libskabus/skabus_rpc_release.lo src/libskabus/skabus_rpc_reply.lo src/libskabus/skabus_rpc_replyv.lo src/libskabus/skabus_rpc_reply_async.lo src/libskabus/skabus_rpc_replyv_async.lo src/libskabus/skabus_rpc_rinfo_pack.lo src/libskabus/skabus_rpc_rinfo_unpack.lo src/libskabus/skabus_rpc_rinfo_zero.lo src/libskabus/skabus_rpc_send.lo src/libskabus/skabus_rpc_send_async.lo src/libskabus/skabus_rpc_send_cb.lo src/libskabus/skabus_rpc_sendpm.lo src/libskabus/skabus_rpc_sendpm_async.lo src/libskabus/skabus_rpc_sendq.lo src/libskabus/skabus_rpc_sendq_async.lo src/libskabus/skabus_rpc_sendv.lo src/libskabus/skabus_rpc_sendv_async.lo src/libskabus/skabus_rpc_sendvpm.lo src/libskabus/skabus_rpc_sendvpm_async.lo src/libskabus/skabus_rpc_sendvq.lo src/libskabus/skabus_rpc_sendvq_async.lo src/libskabus/skabus_rpc_start.lo src/libskabus/skabus_rpc_start_async.lo src/libskabus/skabus_rpc_update.lo src/libskabus/skabus_rpc_zero.lo
endif
libskabus.so.xyzzy: EXTRA_LIBS := -lskarnet
libskabus.so.xyzzy: src/libskabus/skabus_rpc_cancel.lo src/libskabus/skabus_rpc_cancel_async.lo src/libskabus/skabus_rpc_end.lo src/libskabus/skabus_rpc_get.lo src/libskabus/skabus_rpc_idstr.lo src/libskabus/skabus_rpc_idstr_async.lo src/libskabus/skabus_rpc_interface_register.lo src/libskabus/skabus_rpc_interface_register_async.lo src/libskabus/skabus_rpc_interface_register_cb.lo src/libskabus/skabus_rpc_interface_unregister.lo src/libskabus/skabus_rpc_interface_unregister_async.lo src/libskabus/skabus_rpc_interface_zero.lo src/libskabus/skabus_rpc_qinfo_zero.lo src/libskabus/skabus_rpc_qlist.lo src/libskabus/skabus_rpc_qlist_ack.lo src/libskabus/skabus_rpc_r_notimpl.lo src/libskabus/skabus_rpc_rcancel_ignore.lo src/libskabus/skabus_rpc_release.lo src/libskabus/skabus_rpc_reply.lo src/libskabus/skabus_rpc_replyv.lo src/libskabus/skabus_rpc_reply_async.lo src/libskabus/skabus_rpc_replyv_async.lo src/libskabus/skabus_rpc_rinfo_pack.lo src/libskabus/skabus_rpc_rinfo_unpack.lo src/libskabus/skabus_rpc_rinfo_zero.lo src/libskabus/skabus_rpc_send.lo src/libskabus/skabus_rpc_send_async.lo src/libskabus/skabus_rpc_send_cb.lo src/libskabus/skabus_rpc_sendpm.lo src/libskabus/skabus_rpc_sendpm_async.lo src/libskabus/skabus_rpc_sendq.lo src/libskabus/skabus_rpc_sendq_async.lo src/libskabus/skabus_rpc_sendv.lo src/libskabus/skabus_rpc_sendv_async.lo src/libskabus/skabus_rpc_sendvpm.lo src/libskabus/skabus_rpc_sendvpm_async.lo src/libskabus/skabus_rpc_sendvq.lo src/libskabus/skabus_rpc_sendvq_async.lo src/libskabus/skabus_rpc_start.lo src/libskabus/skabus_rpc_start_async.lo src/libskabus/skabus_rpc_update.lo src/libskabus/skabus_rpc_zero.lo
skabus-dyntee: EXTRA_LIBS :=
skabus-dyntee: src/misc/skabus-dyntee.o -lskarnet
skabus-dyntee-client: EXTRA_LIBS := ${SOCKET_LIB}
skabus-dyntee-client: src/misc/skabus-dyntee-client.o -lskarnet
skabus-dynteed: EXTRA_LIBS := ${SOCKET_LIB}
skabus-dynteed: src/misc/skabus-dynteed.o -ls6 -lskarnet
skabus-rpc-client: EXTRA_LIBS :=
skabus-rpc-client: src/rpc/skabus-rpc-client.o -lskarnet
skabus-rpc-daemon: EXTRA_LIBS :=
skabus-rpc-daemon: src/rpc/skabus-rpc-daemon.o -lskarnet
skabus-rpcc: EXTRA_LIBS := ${SOCKET_LIB} ${SYSCLOCK_LIB}
skabus-rpcc: src/rpc/skabus-rpcc.o ${LIBSKABUS} -lskarnet
skabus-rpccctl: EXTRA_LIBS := ${SOCKET_LIB} ${SYSCLOCK_LIB}
skabus-rpccctl: src/rpc/skabus-rpccctl.o src/rpc/skabus_rpccctl.o -lskarnet
skabus-rpcd: EXTRA_LIBS := ${SOCKET_LIB} ${SYSCLOCK_LIB}
skabus-rpcd: src/rpc/skabus-rpcd.o src/rpc/skabus_rpcd_client.o src/rpc/skabus_rpcd_interface.o src/rpc/skabus_rpcd_query.o libskabus.a.xyzzy -ls6 -lskarnet
